export {
  type Vitals,
  DEFAULT_VITALS,
  clamp,
  getVitalsAverage,
  getVitalsStatus,
  getVitalStatus,
  DECAY_RATES,
  applyDecay,
  INTERACTION_EFFECTS,
  type Interaction,
  applyInteraction,
  type TickResult,
  tick,
  multiTick,
  calculateElapsedTicks,
} from '@metapet/core/vitals';
